export let cols = [
  {
    id: "newIcon",
    numeric: false,
    disablePadding: true,
    label: "Icon",
    width: 300,
  },
  {
    id: "barcode",
    numeric: false,
    disablePadding: false,
    label: "Barcode",
    width: 200,
  },
  {
    id: "description",
    numeric: false,
    disablePadding: false,
    label: "Description",
    width: 200,
  },
  {
    id: "short_name",
    numeric: true,
    disablePadding: true,
    label: "Short Name",
    width: 200,
  },
  {
    id: "price",
    numeric: true,
    disablePadding: true,
    label: "Amount($)",
    width: 300,
  },
  {
    id: "category",
    numeric: false,
    disablePadding: true,
    label: "Category",
    width: 300,
  },
  {
    id: "tax",
    numeric: true,
    disablePadding: true,
    label: "Tax(%)",
    width: 300,
  },
  {
    id: "order",
    numeric: true,
    disablePadding: true,
    label: "Order",
    width: 300,
  },
  {
    id: "price_override_allowed",
    numeric: false,
    disablePadding: true,
    label: "Allow Amount Override",
    width: 300,
  },
];
