export let cols = [
    {
      id: "first_name",
      numeric: false,
      disablePadding: false,
      label: "Name",
      width: 300,
    },
    {
      id: "email",
      numeric: false,
      disablePadding: false,
      label: "Email Id",
      width: 300,
    },
    {
      id: "is_superuser",
      numeric: false,
      disablePadding: false,
      label: "Admin User",
      width: 200,
    },
    {
      id: "is_active",
      numeric: false,
      disablePadding: false,
      label: "Active",
      width: 200,
    },
    {
      id: "can_use_portal",
      numeric: false,
      disablePadding: false,
      label: "Can Use Web",
      width: 200,
    },
    {
      id: "can_use_terminal",
      numeric: false,
      disablePadding: false,
      label: "Can Use Terminal",
      width: 200,
    },
    {
      id: "manual_card_entry",
      numeric: false,
      disablePadding: false,
      label: "Manual Card Entry",
      width: 300,
    },
    {
      id: "id",
      numeric: false,
      disablePadding: false,
      label: "User ID",
      width: 300,
    },
  ];