export let cols = [
    {
      id: "newDate",
      numeric: false,
      disablePadding: false,
      label: "Date-time",
      width: 200,
    },
    {
      id: "settlement_status",
      numeric: false,
      disablePadding: false,
      label: "Settelement Status",
      width: 200,
    },
    {
      id: "settled_on",
      numeric: false,
      disablePadding: false,
      label: "Settelement Date",
      width: 200,
    },
    {
      id: "noOfItems",
      numeric: true,
      disablePadding: true,
      label: "No of Items",
      width: 200,
    },
    {
      id: "card_type",
      numeric: false,
      disablePadding: true,
      label: "Payment Type",
      width: 200,
    },
    {
      id: "cc_last4",
      numeric: true,
      disablePadding: true,
      label: "Last 4",
      width: 200,
    },
    {
      id: "amount",
      numeric: false,
      disablePadding: false,
      label: "Amount $",
      width: 200,
    },
    {
      id: "dvc_serial",
      numeric: false,
      disablePadding: true,
      label: "Terminal ID",
      width: 200,
    },
    {
      id: "trs_type",
      numeric: false,
      disablePadding: false,
      label: "Payment Profile",
      width: 200,
    },
    {
      id: "firstName",
      numeric: false,
      disablePadding: false,
      label: "First Name",
      width: 200,
    },
    {
      id: "last_name",
      numeric: false,
      disablePadding: false,
      label: "Last Name",
      width: 200,
    },
    {
      id: "cardNumber",
      numeric: true,
      disablePadding: true,
      label: "Card Number",
      width: 200,
    },
    {
      id: "mid",
      numeric: true,
      disablePadding: true,
      label: "MID",
      width: 200,
    },
    {
      id: "tid",
      numeric: true,
      disablePadding: true,
      label: "TID",
      width: 200,
    },
    {
      id: "tip",
      numeric: true,
      disablePadding: false,
      label: "Tip $",
      width: 200,
    },
    {
      id: "tri_id_name",
      numeric: false,
      disablePadding: false,
      label: "Transaction Items",
      width: 200,
    },
    {
      id: "trs_id",
      numeric: false,
      disablePadding: false,
      label: "Transaction ID",
      width: 300,
    },
    {
      id: "email",
      numeric: false,
      disablePadding: false,
      label: "User",
      width: 200,
    },
    {
      id: "receipt",
      numeric: false,
      disablePadding: true,
      label: "Receipt",
      width: 200,
    },
  ];