export let cols = [
    {
      id: "newDate",
      numeric: false,
      disablePadding: false,
      label: "Date/time",
      width: 200,
    },
    {
      id: "amount",
      numeric: false,
      disablePadding: false,
      label: "Amount",
      width: 200,
    },
    {
      id: "firstName",
      numeric: false,
      disablePadding: false,
      label: "First Name",
      width: 200,
    },
    {
      id: "last_name",
      numeric: false,
      disablePadding: false,
      label: "Last Name",
      width: 200,
    },
    {
      id: "settlement_status",
      numeric: false,
      disablePadding: false,
      label: "Settelement Status",
      width: 200,
    },
    {
      id: "settled_on",
      numeric: false,
      disablePadding: false,
      label: "Settelement Date",
      width: 200,
    },
    {
      id: "payment_url",
      numeric: false,
      disablePadding: false,
      label: "Payment Url",
      width: 200,
    },
    {
      id: "trs_type",
      numeric: false,
      disablePadding: false,
      label: "Transaction type",
      width: 200,
    },
    {
      id: "settled",
      numeric: true,
      disablePadding: true,
      label: "Settled",
      width: 200,
    },
    {
      id: "noOfItems",
      numeric: true,
      disablePadding: true,
      label: "No of Items",
      width: 200,
    },
    {
      id: "cardNumber",
      numeric: true,
      disablePadding: true,
      label: "Card Number",
      width: 200,
    },
    {
      id: "mid",
      numeric: true,
      disablePadding: true,
      label: "M id",
      width: 200,
    },
    {
      id: "tid",
      numeric: true,
      disablePadding: true,
      label: "T id",
      width: 200,
    }
  ];